#!/bin/sh

for file in ./tests/*.c; do
    name=${file##*/}
    printf -- "--------------------\nDOING: %s\n---------------------\n" "$name"
    gcc -o ./"$name".bin ./*.c "$file"
    ./"$name".bin
done

rm ./*.bin
