#!/bin/bash

names=("$@")

if [ -n "$names" ]; then
    for name in "${names[@]}"; do
        file="./tests/${name}_test.c"
        printf -- "--------------------\nDOING: %s\n---------------------\n" \
            "$name"
        cc -std=c23 -o ./"$name".bin ./*.c "$file"
        ./"$name".bin
    done
else

    for file in ./tests/*.c; do
        name=${file##*/}
        printf -- "--------------------\nDOING: %s\n---------------------\n" "$name"
        cc -std=c23 -o ./"$name".bin ./*.c "$file"
        ./"$name".bin
    done

fi

rm ./*.bin
